### ISSUE TITLE
Add Spam Filter

### ISSUE THREAD

**Issue by skorasaurus** [cuyahoga-tap/cuyasurvey-drupal#1]
A legitimate, but minor concern; preventing spam from being submitted into the database. Should we take a proactive approach regarding this ? 

looks like drupal has a pretty mature module already; what's fellow devs experience using the module ? 

http://drupal.org/project/spam

**Comment by jeffschuler** [comment]
Good thinkin.

The Spam module hasn't been ported to Drupal 7 yet, which is the version we're using.
I typically use the Mollom module when I can: better filtering and less configuration.
http://drupal.org/project/mollom
http://mollom.com/

However, Mollom's free version maxes out at 100 correct CAPTCHA submissions per day. It would probably suit our needs, but we should look into alternatives.

**Comment by jeffschuler** [comment]
[Port spam module to Drupal 7](http://drupal.org/node/1063524)

**Comment by jeffschuler** [comment]
http://mollom.com/pricing

**Comment by ghost** [comment]
http://drupal.org/project/antispam might be pretty useful here.  It integrates with services like:

https://akismet.com/

and 

http://www.defensio.com/

which both have highly permissive free tiers for spam protection.

Then, for CAPTCHA, i would suggest recaptcha:

http://drupal.org/project/recaptcha

This uses a google api, so the rate limits are well up into the thousands.

:)

**Comment by jeffschuler** [comment]
(Not sure where those references came from, but...) the County's decision was to nix spam protection for now unless we have issues.
