### ISSUE TITLE
remove Home buttons in Header and Breadcrumbs on Confirmation page

### ISSUE THREAD

**Issue by skorasaurus** [cuyahoga-tap/cuyasurvey-drupal#8]

**Comment by jeffschuler** [comment]
Added ability to theme to be able to disable breadcrumbs, ([commit](368a0b9e0bfef60bd5d02af6c0b094dfbb9668e9) and [patch on drupal.org](http://drupal.org/node/1306534#comment-5555688)) and applied configuration to staging and production sites.

Leaving the Home button in the header.
